### ISSUE TITLE
Bad link to tutorials

### ISSUE THREAD

**Issue by joelongstreet** [openrndr/openrndr.org#1]
I've noticed on the home page of https://openrndr.org/, within the "Getting Started" section, in the "Tutorials" column, the link "GO TO TUTORIALS" is bad.

It currently navigates to https://guide.openrndr.org/#/Topic_TutorialRepository, thinking it should navigate to https://guide.openrndr.org/#/02_Getting_Started_with_OPENRNDR/C01_TutorialRepository or https://github.com/openrndr/openrndr-tutorials?

Was thinking of making a PR to fix, but I couldn't find the link anywhere in the codebase. Must be controlled by the DatoCMS?

**Comment by hamoid** [comment]
This seems to be an issue again. Both tutorial links on the home page take you to 404 pages. Also, the error message is barely visible because the color is to similar to the background color.
